default: &default  
  adapter: postgresql  
  encoding: unicode  
  pool: 5  
  username: postgres
  password: "12345678"
  host: localhost  
  port: 5432

development:  
  <<: *default  
  database: revv-challenge-app_development

test:  
  <<: *default  
  database: revv-challenge-app_test

production:  
  <<: *default
  username: root
  password: 
  url: <%= ENV['DATABASE_URL'] %>